# Generated by Django 2.2.8 on 2021-02-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desiderata', '0002_auto_20210217_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='desiderata',
            name='video',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
