# Generated by Django 2.2.8 on 2021-02-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desiderata', '0003_desiderata_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desiderata',
            options={'ordering': ['ordering', 'name']},
        ),
    ]
